name: Build RSS Guard Windows

on:
  push:
    branches:
      - main
      - master
  pull_request:

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Qt 6.6.3 MSVC 64-bit
      uses: jurplel/install-qt-action@v2
      with:
        version: '6.6.3'
        host: 'windows'
        arch: 'win64_msvc'
        target: 'desktop'

    - name: Install vcpkg dependencies
      run: |
        git clone https://github.com/microsoft/vcpkg.git vcpkg
        .\vcpkg\bootstrap-vcpkg.bat
        .\vcpkg\vcpkg integrate install
        .\vcpkg\vcpkg install qt6-base:x64-windows

    - name: Configure CMake
      run: cmake -S . -B build -G "Visual Studio 17 2022" -A x64 -DCMAKE_PREFIX_PATH=%USERPROFILE%\Qt\6.6.3\msvc2019_64\lib\cmake

    - name: Build solution
      run: cmake --build build --config Release

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: rssguard-windows-exe
        path: build\Release\RssGuard.exe
