name: Build RSS Guard

on:
  push:
    branches:
      - devbuild
      - master
  pull_request:
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup Qt 6.6.3 MSVC 64-bit
      uses: jurplel/install-qt-action@v2
      with:
        version: '6.6.3'
        host: 'windows'
        arch: 'win64_msvc'

    - name: Configure CMake
      run: cmake -S . -B build -G Ninja -DCMAKE_BUILD_TYPE=Release

    - name: Build solution
      run: cmake --build build --config Release

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: rssguard-windows-exe
        path: build\RssGuard.exe
